flask001_blog/models.py
from flask_sqlalchemy import SQLAlchemy
# from flask001_blog.__init__ import app # 初始化后不需要了
# from sqlalchemy import *  # 此方法可以省略部分代码，尚未测试
from .extensions import bcrypt

db = SQLAlchemy()  # 在pycharm2017中可以正常使用，并且db.Column可以正常提示

# a=Column(String(45),)


class User(db.Model):

    __tablename__ = 'users'
    id = db.Column(db.String(45), primary_key=True)
    username = db.Column(db.String(255))
    password = db.Column(db.String(255))

    posts = db.relationship(
        'Post',
        backref='users',
        lazy='dynamic')

    # 教程中这个函数写在__init__之后导致函数无法使用，调整后通过
    def set_password(self, password):
        return bcrypt.generate_password_hash(password)

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)

    def __init__(self, id, username, password):
        self.id = id
        self.username = username
        # byte和str互相转化？？？,加个decode()就解决了
        self.password = self.set_password(password).decode()

    def __repr__(self):
        return "<Model User '{}'>".format(self.username)


posts_tags = db.Table('posts_tags',
    db.Column('post_id', db.String(45), db.ForeignKey('posts.id')),
    db.Column('tag_id', db.String(45), db.ForeignKey('tags.id')))


class Post(db.Model):

    __tablename__ = 'posts'
    id = db.Column(db.String(45), primary_key=True)
    title = db.Column(db.String(355))
    text = db.Column(db.Text())
    created_date = db.Column(db.DateTime)

    user_id = db.Column(db.String(45), db.ForeignKey('users.id'))

    comments = db.relationship(
        'Comment',
        backref='posts',
        lazy='dynamic')

    tags = db.relationship(
        'Tag',
        secondary='posts_tags',
        backref=db.backref('posts', lazy='dynamic'))

    def __init__(self, id, title):
        self.id = id
        self.title = title

    def __repr__(self):  # 命令行修改语句
        return "<Model Post '{}'>".format(self.title)


class Comment(db.Model):

    __tabelname__ = 'comments'
    id = db.Column(db.String(45), primary_key=True)
    name = db.Column(db.String(255))
    text = db.Column(db.Text())
    created_time = db.Column(db.DateTime())

    post_id = db.Column(db.String(45), db.ForeignKey('posts.id'))

    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __repr__(self):
        return "<Model Comment '{}'>".format(self.name)


class Tag(db.Model):

    __tablename__ = 'tags'
    id = db.Column(db.String(45), primary_key=True)
    name = db.Column(db.String(255))

    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __repr__(self):
        return "<Model Tag '{}'>".format(self.name)

flask001_blog/forms.py
from flask_wtf import Form
from wtforms import (
    StringField,
    TextField,
    TextAreaField,
    PasswordField,
    BooleanField,
    ValidationError
)
from wtforms.validators import DataRequired, Length, EqualTo, URL

from .models import User


class LoginForm(Form):
    username = StringField('Username', [DataRequired(), Length(max=255)])
    password = PasswordField('Password', [DataRequired()])

    def validate(self):
        check_validate = super(LoginForm, self).validate()

        if not check_validate:
            return False

        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append('此用户不存在，请重新输入用户名')
            return False

        if not user.check_password(self.password.data):
            self.username.errors.append('密码错误：请重新输入密码')
            return False

        return True


class RegisterForm(Form):
    username = StringField('Username', [DataRequired(), Length(max=255)])
    # 注意此处的min=8，由于没有提示信息导致测试时卡在这里没想明白,当密码小于8位页面不会跳转
    password = PasswordField('Password', [DataRequired(), Length(min=8)])
    password2 = PasswordField('Password_again', [DataRequired(),
                                                 EqualTo('password')])
    # recaptcha =

    def validate(self):
        check_validate = super(RegisterForm, self).validate()

        if not check_validate:
            return False

        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('用户已存在')
            return False
        return True


class PostForm(Form):
    title = StringField('Title', [DataRequired(), Length(max=255)])
    text = TextAreaField('Blog Content', [DataRequired()])


class CommentForm(Form):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )

    text = TextField(u'Comment', validators=[DataRequired()])

flask001_blog/__init__.py
from flask import Flask, redirect, url_for

from .models import db
from .controllers import blog, main
from .extensions import bcrypt


def create_app(object_name):

    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    bcrypt.init_app(app)

    app.register_blueprint(blog.blog_blueprint)
    app.register_blueprint(main.main_blueprint)

    return app

flask001_blog/controllers/blog.py
from flask import render_template, Blueprint
from sqlalchemy import func

from uuid import uuid4
import datetime
from os import path

from flask001_blog.models import db, User, Post, Tag, Comment, posts_tags
from flask001_blog.forms import CommentForm


blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder=path.join(path.pardir, 'templates', 'blog'),
    url_prefix='/blog')  # 最后一个参数为路由前缀，localhost/blog/<ID>


def sidebar_data():

    recent = db.session.query(Post).order_by(
        Post.created_date.desc()
    ).limit(5).all()

    top_tags = db.session.query(
        Tag, func.count(posts_tags.c.post_id).label('total')
    ).join(posts_tags).group_by(Tag).order_by('total DESC').limit(5).all()

    return recent, top_tags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
def home(page=1):
    posts = Post.query.order_by(
        Post.created_date.desc()
    ).paginate(page, 10)

    recent, top_tags = sidebar_data()

    return render_template('home.html',
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/post/<string:post_id>', methods=('GET', 'POST'))
def post(post_id):

    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment(id=str(uuid4()),
                              name=form.name.data)
        new_comment.text = form.text.data
        new_comment.created_time = datetime.datetime.now()
        new_comment.post_id = post_id
        db.session.add(new_comment)
        db.session.commit()

    post = Post.query.get_or_404(post_id)
    tags = post.tags
    comments = post.comments.order_by(Comment.created_time.desc()).all()
    recent, top_tags = sidebar_data()
    return render_template('post.html',
                           post=post,
                           tags=tags,
                           comments=comments,
                           form=form,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/tag/<string:tag_name>')
def tag(tag_name):

    tag = db.session.query(Tag).filter_by(name=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.created_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('tag.html',
                           tag=tag,
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)


@blog_blueprint.route('/user/<string:username>')
def user(username):

    user = db.session.query(User).filter_by(username=username).first_or_404()
    posts = user.posts.prder_by(Post.created_date.desc()).all()
    recent, top_tags = sidebar_data()

    return render_template('user.html',
                           user=user,
                           posts=posts,
                           recent=recent,
                           top_tags=top_tags)

flask001_blog/controllers/main.py
from os import path
from uuid import uuid4

from flask import flash, url_for, redirect, render_template, Blueprint

from flask001_blog.forms import LoginForm, RegisterForm
from flask001_blog.models import db, User


main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder=path.join(path.pardir, 'templates', 'main'))


# @main_blueprint.route('/')
# def index():
#     return redirect(url_for('blog.home'))
@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        flash('登入成功', category='Success')
        return redirect(url_for('blog.home'))

    return render_template('login.html', form=form)


@main_blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
    flash('成功退出账号', category='Success')
    return redirect(url_for('blog.home'))


@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        new_user = User(id=str(uuid4()),
                        username=form.username.data,
                        password=form.password.data)

        db.session.add(new_user)
        db.session.commit()

        flash('注册成功', category='success')
        return redirect(url_for('main.login'))

    return render_template('register.html', form=form)

flask001_blog/templates/blog/base.html
<!DOCTYPE html>

<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,, initial-scale=1">
    <!-- Will be replace the page title -->
    <title>{% block title %}Home{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <!-- Macro: `render paginate` -->
    {% macro render_pagination(pagination, endpoint) %}
    <nav>
        <ul class="pagination">
            <li>
                {% if pagination.has_prev %}
                <a href="{{ url_for('blog.home', page=pagination.prev().page)}}" aria-label="Previous">
                    {% else %}
                    <a href="{{ url_for('blog.home', page=1) }}" aria-label="Previous">
                        {% endif %}
                        <span aria-label="true">&laquo;</span>
                    </a>
                </a>
            </li>
            {% for page in pagination.iter_pages() %}
            {% if page %}
            {% if page != pagination.page %}
            <li>
                <a href="{{ url_for(endpoint, page=page) }}">
                    {{ page }}
                </a>
            </li>
            {% else %}
            <li><a href="">{{ page }}</a></li>
            {% endif %}
            {% else %}
            <li><a>...</a></li>
            {% endif %}
            {% endfor %}
            <li>
                <a href="{{ url_for('blog.home', page=pagination.next().page )}}" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            <li>
        </ul>
    </nav>
    {% endmacro %}
</head>
<body>
<div class="container">
    <div class="jumbotron">
        <!-- Replace the route function to URL: `/` -->
        <h1><a href="{{ url_for('blog.home')}} ">6167's Blog</a></h1>
        <p>Welcome to the blog!</p>
    </div>
    {% block body %}
    body_content
    {% endblock %}
</div>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

flask001_blog/templates/blog/home.html
{% extends "base.html"%}
{% block title %}6167's blog{%endblock%}


{% block body %}
<!-- The data object from view function: `home()` -->
<div class="row">
    <div class="col-lg-9">
        <!-- Get Pagination object-->
        {% for post in posts.items %}
        <div class="row">
            <div class="col-lg-12">
                <h1>{{ post.title }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                {{ post.text | truncate(255) | safe }}
                <!-- Set the link for read more -->
                <a href="{{url_for('blog.post', post_id=post.id)}}">Read More</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-lg-3">
        <div class="row">
            <h5>Recent Posts</h5>
            <ul>
                {% for post in recent %}
                <!-- Set the link for recent posts. -->
                <li><a href="{{url_for('blog.post', post_id=post.id)}}">{{ post.title }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <div class="row">
            <h5>Popular Tags</h5>
            <ul>
                {% for tag in top_tags %}
                <li><a href="{{url_for('blog.tag', tag_name=tag[0].name)}}">{{ tag[0].name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <!-- Call the Macro: `render_pagination` from base.html -->
    {{ render_pagination(posts, 'blog.home') }}
</div>
{% endblock %}

flask001_blog/templates/blog/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% extends "base.html"%}
        {% block title %}{{ post.name }}{% endblock %}
    </title>
</head>

<body>
{% block body %}
<h3>{{ post.title }}</h3>
{{ post.publish_date }}:
{{ post.text }}

<div class="col-lg-12">
    <h3>New Comment:</h3>
    <!-- Set the form -->
    <form method="POST" action="{{ url_for('blog.post', post_id=post.id)}}">
        {{ form.hidden_tag() }}
        <div>
            <!-- Field: `name` label -->
            {{ form.name.label }}
            {% if form.name.errors %}
            {% for e in form.name.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.name(class_="form-control") }}
        </div>
        <div class="form-group">
            {{ form.text.label }}
            {% if form.text.errors %}
            {% for e in form.text.errors %}
            <p class="help-block">{{ e }}</p>
            {% endfor %}
            {% endif %}
            {{ form.text(class_='form-control') }}
        </div>
        <input class="btn btn-primary" type="submit" value="Add Comment">
    </form>
</div>
{% endblock %}
</body>
</html>